//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS_Book_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string UserName { get; set; }
        public string RecipientAddress { get; set; }
        public string RecipientPhone { get; set; }
        public string RecipientName { get; set; }
        public Nullable<int> TotalValue { get; set; }
        public string OrderNote { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual DetailOrder DetailOrder { get; set; }
        public virtual StatusObject StatusObject { get; set; }
    }
}
