//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS_Book_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string CommentContent { get; set; }
        public Nullable<bool> IsReply { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual StatusObject StatusObject { get; set; }
    }
}
